Repository kubernetes-sigs/depstat, pull requests merged in 2021-05, with the labels that each got.

#40 added version field in root command
  cmd/root.go
Labels: approved, cncf-cla: yes, size/XS

#41 updating release.md with the current release process
  RELEASE.md
Labels: approved, cncf-cla: yes, size/S

#42 Wrap main graph properties into a struct
  cmd/cycles.go
  cmd/graph.go
  cmd/list.go
  cmd/stats.go
  cmd/utils.go
  cmd/utils_test.go
Labels: approved, cncf-cla: yes, size/M
